import { Background, Person, WithRarity } from "./attribute-types";

export const backgrounds: WithRarity<Background> = {
  'MCLNY_Background_StyleA_Blue 1.png': ['Cadet Blue', 'Common'],
  'MCLNY_Background_StyleA_Purple 1.png': ['Explorer Purple', 'Rare'],
  'MCLNY_Background_StyleA_Violet 1.png': ['Atlas Red', 'Legendary'],
};

export const persons: WithRarity<Person> = {
  'MCLNY_Female_TypeA_Alpha 1.png':        ['Female; Type - A; Hair - 1', 'Common'],
  'MCLNY_Female_TypeA_Hair01_Alpha 1.png': ['Female; Type - A; Hair - 2', 'Common'],
  'MCLNY_Female_TypeA_Hair02_Alpha 1.png': ['Female; Type - A; Hair - 3', 'Common'],
  'MCLNY_Female_TypeB_Alpha 1.png':        ['Female; Type - B; Hair - 1', 'Common'],
  'MCLNY_Female_TypeB_Hair01_Alpha 1.png': ['Female; Type - B; Hair - 2', 'Common'],
  'MCLNY_Female_TypeB_Hair02_Alpha 1.png': ['Female; Type - B; Hair - 3', 'Common'],
  'MCLNY_Female_TypeC_Alpha 1.png':        ['Female; Type - C; Hair - 1', 'Common'],
  'MCLNY_Female_TypeC_Hair01_Alpha 1.png': ['Female; Type - C; Hair - 2', 'Common'],
  'MCLNY_Female_TypeC_Hair02_Alpha 1.png': ['Female; Type - C; Hair - 3', 'Common'],
  'MCLNY_Female_TypeD_Alpha 1.png':        ['Female; Type - D; Hair - 1', 'Common'],
  'MCLNY_Female_TypeD_Hair01_Alpha 1.png': ['Female; Type - D; Hair - 2', 'Common'],
  'MCLNY_Female_TypeD_Hair02_Alpha 1.png': ['Female; Type - D; Hair - 3', 'Common'],
  'MCLNY_Female_TypeE_Alpha 1.png':        ['Female; Type - E; Hair - 1', 'Common'],
  'MCLNY_Female_TypeE_Hair01_Alpha 1.png': ['Female; Type - E; Hair - 2', 'Common'],
  'MCLNY_Female_TypeE_Hair02_Alpha 1.png': ['Female; Type - E; Hair - 3', 'Common'],
  'MCLNY_Male_TypeA_Alpha 1.png':          ['Male; Type - A; Hair - 1', 'Common'],
  'MCLNY_Male_TypeA_Hair02_Alpha 1.png':   ['Male; Type - A; Hair - 2', 'Common'],
  'MCLNY_Male_TypeA_Hair03_Alpha 1.png':   ['Male; Type - A; Hair - 3', 'Common'],
  'MCLNY_Male_TypeB_Alpha 1.png':          ['Male; Type - B; Hair - 1', 'Common'],
  'MCLNY_Male_TypeB_Hair01_Alpha 1.png':   ['Male; Type - B; Hair - 2', 'Common'],
  'MCLNY_Male_TypeB_Hair02_Alpha 1.png':   ['Male; Type - B; Hair - 3', 'Common'],
  'MCLNY_Male_TypeC_Alpha 1.png':          ['Male; Type - C; Hair - 1', 'Common'],
  'MCLNY_Male_TypeC_Hair02_Alpha 1.png':   ['Male; Type - C; Hair - 2', 'Common'],
  'MCLNY_Male_TypeC_Hair03_Alpha 1.png':   ['Male; Type - C; Hair - 3', 'Common'],
  'MCLNY_Male_TypeD_Alpha 1.png':          ['Male; Type - D; Hair - 1', 'Common'],
  'MCLNY_Male_TypeD_Hair01_Alpha 1.png':   ['Male; Type - D; Hair - 2', 'Common'],
  'MCLNY_Male_TypeD_Hair02_Alpha 1.png':   ['Male; Type - D; Hair - 3', 'Common'],
  'MCLNY_Male_TypeE_Alpha 1.png':          ['Male; Type - E; Hair - 1', 'Common'],
  'MCLNY_Male_TypeE_Hair01_Alpha 1.png':   ['Male; Type - E; Hair - 2', 'Common'],
  'MCLNY_Male_TypeE_Hair02_Alpha 1.png':   ['Male; Type - E; Hair - 3', 'Common'],
  'MCLNY_Female_TypeA_Hair03_Alpha 1.png': ['Female; Type - A; Hair - 4', 'Rare'],
  'MCLNY_Female_TypeB_Hair03_Alpha 1.png': ['Female; Type - B; Hair - 4', 'Rare'],
  'MCLNY_Female_TypeC_Hair03_Alpha 1.png': ['Female; Type - C; Hair - 4', 'Rare'],
  'MCLNY_Female_TypeD_Hair03_Alpha 1.png': ['Female; Type - D; Hair - 4', 'Rare'],
  'MCLNY_Female_TypeE_Hair03_Alpha 1.png': ['Female; Type - E; Hair - 4', 'Rare'],
  'MCLNY_Male_TypeA_Hair01_Alpha 1.png':   ['Male; Type - A; Hair - 4', 'Rare'],
  'MCLNY_Male_TypeB_Hair03_Alpha 1.png':   ['Male; Type - B; Hair - 4', 'Rare'],
  'MCLNY_Male_TypeC_Hair01_Alpha 1.png':   ['Male; Type - C; Hair - 4', 'Rare'],
  'MCLNY_Male_TypeD_Bald02_Alpha 1.png':   ['Male; Type - D; Hair - 4', 'Rare'],
  'MCLNY_Male_TypeE_Hair03_Alpha 1.png':   ['Male; Type - E; Hair - 4', 'Rare'],
  'MCLNY_Female_TypeA_Alpha_Legendary 1.png': ['Female; Type - A; Hair - Pink hair', 'Legendary'],
  'MCLNY_Female_TypeC_Alpha_Legendary 1.png': ['Female; Type - C; Hair - Blue hair', 'Legendary'],
  'MCLNY_Female_TypeE_Alpha_Legendary 1.png': ['Female; Type - E; Hair - 5; Solar Iris', 'Legendary'],
  'MCLNY_Male_TypeB_Alpha_Legendary 1.png':   ['Male; Type - B; Hair - 5; Scar', 'Legendary'],
  'MCLNY_Male_TypeC_Alpha_Legendary 1.png':   ['Male; Type - C; Hair - 5; Solar Iris', 'Legendary'],
  'MCLNY_Male_TypeE__Alpha_Legendary 1.png':  ['Male; Type - E; Hair - 5; Solar Iris', 'Legendary'],
};

